name: Cypress Tests
on: [push]
jobs:
  cypress-run:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2
 
     - name: Run Cypress Test
       uses: cypress-io/github-action@v2.2.7
       with:
         command: npm run ui-regreshion
         browser: chrome

    - name: Copy test execution videos
      run: |
        mkdir public
        cp -r cypress/videos public/videos

    - name: Merge test results into one
      run: npm run report:merge

    - name: Generate HTML report
      run: npm run report:generate

    - name: Deploy report page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        user_name: 'dkhomyshyn'
        user_email: 'dkhomyshyn@mycubes.nl'